/* This file was automatically generated by ./configure */

#define XRANDR_MAJOR 1
#define XRANDR_MINOR 4
#define XRANDR_PATCH 2

#define SPLIT_SCREEN_HEIGHT 1080
#define SPLIT_SCREEN_WIDTH  1920
#define REAL_XRANDR_LIB "/usr/lib/x86_64-linux-gnu/libXrandr.so.2"
#define FAKEXRANDR_INSTALL_DIR "/usr/local/lib"
